[fix] Update to Ruby 3.2
Signed-off-by: Carlos Nunez <13461447+carlosonunez@users.noreply.github.com>

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -1,10 +1,14 @@
 #!/usr/bin/env bash
 
-if test -e "$(dirname "$0")/../.env"
+# shellcheck disable=SC2046
+ENV_FILE="${ENV_FILE:-$(dirname "$0")/../${ENV_FILE}}"
+if ! test -e "$ENV_FILE"
 then
-  # shellcheck disable=SC2046
-  export $(grep -Ev '^#' .env | xargs -0)
+  >&2 echo "ERROR: Env file not found: $ENV_FILE"
+  exit 1
 fi
+eval $(sed -e '/^#/d;/^\s*$/d' -e "s/'/'\\\''/g" -e "s/=\(.*\)/='\1'/g" "${ENV_FILE}")
+unset AWS_SESSION_TOKEN
 
 set -e
 export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID?Please define AWS_ACCESS_KEY_ID.}"
@@ -32,7 +36,7 @@ export AWS_ACCESS_KEY_ID="$access_key"
 export AWS_SECRET_ACCESS_KEY="$secret_key"
 export AWS_SESSION_TOKEN="$session_token"
 
-docker-compose run -T --rm vendor
+docker-compose run -T --rm vendor || exit 1
 case "$ENVIRONMENT" in
   test)
     for stage in deploy-serverless-infra-test deploy-serverless-functions-test
@@ -48,7 +52,7 @@ case "$ENVIRONMENT" in
   production)
     for stage in deploy-serverless-infra deploy-serverless-domain deploy-serverless-functions
     do
-      docker-compose -f docker-compose.deploy.yml run -T -e ENVIRONMENT=production --rm "$stage"
+      docker-compose -f docker-compose.deploy.yml run -T -e ENVIRONMENT=production --rm "$stage" || exit 1
     done
     ;;
   *)
